### PR TITLE
Standardize on `-Drewrite.` prefixed properties on the commandline

### PR DESCRIPTION
**Pull request by ghusta**
Fixes: #722

### CODE REVIEW

**Comment by timtebeek** [comment]
There's a small change to the order of recipes as reported in the logs, but other than that this looks good. Thanks for getting this started!

**Comment by ghusta** [comment]
OK test failing because I didn't use LinkedHashSet to preserve order of recipes...

**Comment by timtebeek** [comment]
Thanks a lot @ghusta ! Took your initial changes as an opportunity to consistently deprecate all such duplicated properties, and apply some more clean ups throughout. Would appreciate it if you could review if I indeed understood your docs in #722 correctly, or if there was any reason you'd held off on changing the other properties too.

**Review by timtebeek — APPROVED** [review]
Thanks again @ghusta ! Should help prevent any confusion about what properties to use going forward.

**Comment by ghusta** [comment]
Thank you for your great cooperation when working on this PR.

**Comment by timtebeek** [comment]
Yes really liked how you provided all the context to your proposed changes, and we now nudge folks towards the prefixed properties without breaking current use.

Hope to see you contribute again, this was great to see & review. :)

**Pull request merged**
