### PR TITLE
Add test to reproduce wrong version of netty-handler

### PR DESCRIPTION
**Pull request by algomaster99**
## What's changed?

- Added a test
- Added a submodule https://github.com/vmi/selenese-runner-java/tree/3e84e8e4e7e06aa1bdacaa8266db00f62ebef559

## What's your motivation?

Reproduce #566 .

## Anything in particular you'd like reviewers to focus on?

The version of `io.netty:netty-handler` reported is `4.1.78.Final`, which is incorrect based on `maven-dependency-plugin:3.4.0:tree` as reported [here](https://github.com/chains-project/SBOM-2023/blob/major-revision/sbom-production/results/selenese-runner-java/maven-dependency-tree/tree.json?rgh-link-date=2023-05-31T17%3A48%3A09Z). However, I looked up where this dependency comes from, and it is a direct dependency of https://mvnrepository.com/artifact/io.netty/netty-codec-http/4.1.78.Final. Surprisingly, maven central also reports the version as `4.1.78.Final`.

## Anyone you would like to review specifically?

@joanvr 
## Any additional context

I am actually doing a study of SBOM producers and we included your tool in our analysis. You can find the full technical report here - https://arxiv.org/pdf/2303.11102.pdf. We came across this variance in behaviour while looking through different SBOMs.

### Checklist
- [x] I've added unit tests to cover both positive and negative cases
- [ ] I've added the license header to any new files through `./gradlew licenseFormat`
- [x] I've used the IntelliJ auto-formatter on affected files
- [ ] I've updated the documentation (if applicable)

### CODE REVIEW

**Comment by timtebeek** [comment]
Hi @algomaster99 ! Appreciate you took the time to inform us in detail of this issue with our SBOM report. For inclusion in our project I hope there's a way to replicate this without the need for a git submodule, although I'd understand it if you're not inclined to reduce this further on your own time. Know that we're thankful of the report and hope to have this resolved.

**Comment by algomaster99** [comment]
Hi @timtebeek !

Sorry for the late response, but it has been holiday season here in Sweden. However, I can give a try to generate a minimal example, but I am not sure why this is happening firstly. My only guess right now is that the dependency tree contains two different versions of `netty-handler`, and maven just chooses the latest one.If this is the case, an SBOM producer should report both versions.

**Comment by timtebeek** [comment]
No problem at all & thank you for getting back to us whenever it fits your schedule. It's an interesting theory, and even if there are multiple versions we should still match what Maven does for our reports. Hope we can reproduce this in a smaller sample which we can then ideally fit into our unit tests.

**Comment by timtebeek** [comment]
Closing this one as discussed: ideally we replicate this without the need for a submodule. The Mojo here uses a utility in openrewrite/rewrite, so any improvements are likely to go there as well:
https://github.com/openrewrite/rewrite/blob/v8.10.1/rewrite-maven/src/main/java/org/openrewrite/maven/utilities/PrintMavenAsCycloneDxBom.java

Thanks again for bringing forth this issue!

**Pull request closed without merging**
